services:
  web:
    image: ct2em/fbi-watchlist-client
    build: ./client
    ports:
      - "3000:3000"
    volumes:
     - .:/client
    environment:
      NODE_ENV: development
    command: yarn dev

  api:
    image: ct2em/fbi-watchlist-server
    build: ./server
    ports: 
      - "5000:5000"
    volumes:
      - .:/server
      - '/server/node_modules'
    environment:
      NODE_ENV: dev
      SERVER_PORT: 5000
      command: yarn dev
