version: '3.8'

services:
  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
     - .:/client
    environment:
      NODE_ENV: development
    command: yarn dev

  api:
    build: ./server
    ports: 
      - "5000:5000"
    volumes:
      - .:/server
    environment:
      NODE_ENV: dev
      SERVER_PORT: 5000
      command: yarn dev

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: fbi_most_wanted_watchlist_db
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: postgres
      # You can use whatever password you like
      POSTGRES_PASSWORD: postgres
      # Password for root access
      POSTGRES_ROOT_PASSWORD: postgres
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '5431:5432'
    expose:
      # Opens port 5432 on the container
      - '5431'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/postgres
# Names our volume
volumes:
  my-db: