const data: unknown[] = [
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/counterintelligence/boris-yakovlevich-livshits/download.pdf",
        name: "English",
      },
      {
        url: "https://www.fbi.gov/wanted/counterintelligence/boris-yakovlevich-livshits/livshitsrussian.pdf/@@download/file/livshitsrussian.pdf",
        name: " ",
      },
    ],
    age_range: null,
    uid: "b953c05b852a4b719c0a152ef8a73ffd",
    weight: null,
    occupations: ["Electrical Engineer"],
    field_offices: ["newyork"],
    locations: null,
    reward_text: null,
    sex: "Male",
    hair: "black",
    ncic: null,
    dates_of_birth_used: ["May 9, 1970"],
    caution:
      '<p>Boris Yakovlevich Livshits is wanted for his alleged involvement in the Russian-backed procurement network Serniya/Sertal from 2017 to 2022. Livshits and his co-conspirators allegedly unlawfully sourced, purchased, and shipped military and sensitive dual-use technologies from United States manufacturers to Russian end users. These items included advanced testing equipment used in quantum computing, hypersonic missiles, nuclear weapons development, and other military and space-based military applications.</p>\r\n<p> </p>\r\n<p>Serniya’s clients included the National Research Nuclear University of the Moscow Engineering Physics Institute; the Ministry of Defense; the Foreign Intelligence Service ("SVR"); and various components of the Federal Security Service ("FSB"), Russia\'s principal security agency and the main successor agency to the Soviet Union\'s KGB.</p>\r\n<p> </p>\r\n<p>Livshits allegedly controlled several American and international front companies that operated on behalf of the Serniya Network. These entities conducted no actual business and were allegedly used to obfuscate the role of Russian or sanctioned entities in transactions with American and Western technology companies. Livshits allegedly facilitated the financing and smuggling of tens of thousands of controlled, American-manufactured military grade sniper bullets and rounds.  Livshits was indicted by the United States District Court, Eastern District of New York, Brooklyn, New York, on December 5, 2022, and a federal warrant was issued for his arrest.</p>\r\n<p> </p>',
    nationality: "Russian",
    age_min: null,
    age_max: null,
    scars_and_marks: null,
    subjects: ["Counterintelligence"],
    aliases: ["Boris Levitan", "Boris Livshitc", "David Wetzky"],
    race_raw: "White",
    suspects: null,
    publication: "2022-12-01T12:17:00",
    title: "BORIS YAKOVLEVICH LIVSHITS",
    coordinates: [],
    hair_raw: "Black / Bald",
    languages: ["Russian", "English"],
    complexion: null,
    build: null,
    details: null,
    status: "na",
    legat_names: null,
    eyes: null,
    person_classification: "Main",
    description:
      "Conspiracy to Defraud the United States; Conspiracy to Violate the International Emergency Economic Powers Act (IEEPA); Bank Fraud Conspiracy; Wire Fraud Conspiracy; Wire Fraud; Money Laundering Conspiracy; Money Laundering; Conspiracy to Violate the Export Control Reform Act (ECRA); Smuggling Goods from the United States; Failure to File Electronic Export Information",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/counterintelligence/boris-yakovlevich-livshits/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/counterintelligence/boris-yakovlevich-livshits/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/counterintelligence/boris-yakovlevich-livshits/@@images/image",
      },
    ],
    possible_countries: null,
    weight_min: null,
    additional_information: null,
    remarks:
      "<p>Livshits has ties to Russia, Estonia, Finland, Kazakhstan, Germany, Latvia, Lithuania, and the United States.  </p>",
    path: "/wanted/counterintelligence/boris-yakovlevich-livshits",
    eyes_raw: null,
    weight_max: null,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/counterintelligence/boris-yakovlevich-livshits",
    possible_states: null,
    modified: "2025-01-21T00:05:21+00:00",
    reward_max: 0,
    race: "white",
    height_max: null,
    place_of_birth: "Leningrad, Russia",
    height_min: null,
    poster_classification: "default",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/b953c05b852a4b719c0a152ef8a73ffd",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/vicap/missing-persons/jesus-de-la-cruz---lynn-massachusetts/delacruz.pdf",
        name: "English",
      },
    ],
    age_range: "6 years old (at time of disappearance)",
    uid: "b166d627e11149aa82c02d1533e3b650",
    weight: "60 pounds (at time of disappearance)",
    occupations: null,
    field_offices: null,
    locations: null,
    reward_text: null,
    sex: "Male",
    hair: "brown",
    ncic: null,
    dates_of_birth_used: null,
    caution: null,
    nationality: null,
    age_min: 6,
    age_max: 6,
    scars_and_marks: null,
    subjects: ["ViCAP Missing Persons"],
    aliases: null,
    race_raw: "White (Hispanic)",
    suspects: null,
    publication: "2021-09-28T10:00:00",
    title: "JESUS DE LA CRUZ - LYNN, MASSACHUSETTS",
    coordinates: [],
    hair_raw: "Brown",
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>Jesus de la Cruz was last seen on September 28, 1996, walking on Park Street near his residence in Lynn, Massachusetts. He was six years old at the time of his disappearance and has not been seen since. De la Cruz has a scar above his left eye, birthmarks on his left calf and the left side of his forehead, and his left ear is pierced. He was last seen wearing a white t-shirt, blue jeans, and brown and yellow boots.</p>\r\n<p> </p>",
    status: "na",
    legat_names: null,
    eyes: "brown",
    person_classification: "Main",
    description: "September 28, 1996\r\nLynn, Massachusetts",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/jesus-de-la-cruz---lynn-massachusetts/@@images/image/large",
        caption: "Photograph taken at Time of Disappearance",
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/jesus-de-la-cruz---lynn-massachusetts/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/jesus-de-la-cruz---lynn-massachusetts/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/jesus-de-la-cruz---lynn-massachusetts/delacruzage.jpg/@@images/image/large",
        caption: "Photograph Age Progressed to 31 Years Old",
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/jesus-de-la-cruz---lynn-massachusetts/delacruzage.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/jesus-de-la-cruz---lynn-massachusetts/delacruzage.jpg",
      },
    ],
    possible_countries: null,
    weight_min: 60,
    additional_information: null,
    remarks:
      "<p>De la Cruz has a scar above his left eye, birthmarks on his left calf and the left side of his forehead, and has his left ear pierced.</p>",
    path: "/wanted/vicap/missing-persons/jesus-de-la-cruz---lynn-massachusetts",
    eyes_raw: "Brown",
    weight_max: 60,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/vicap/missing-persons/jesus-de-la-cruz---lynn-massachusetts",
    possible_states: null,
    modified: "2025-01-21T00:05:21+00:00",
    reward_max: 0,
    race: "hispanic",
    height_max: 54,
    place_of_birth: null,
    height_min: 54,
    poster_classification: "default",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/b166d627e11149aa82c02d1533e3b650",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland/mcgehrin.pdf",
        name: "English",
      },
    ],
    age_range: "36 years old (at time of disappearance)",
    uid: "1584feee758e4cd39136171ef1c007f9",
    weight: "190 pounds",
    occupations: null,
    field_offices: null,
    locations: null,
    reward_text: null,
    sex: "Male",
    hair: "brown",
    ncic: null,
    dates_of_birth_used: null,
    caution: null,
    nationality: null,
    age_min: 36,
    age_max: 36,
    scars_and_marks: null,
    subjects: ["ViCAP Missing Persons"],
    aliases: null,
    race_raw: "White",
    suspects: null,
    publication: "2022-03-21T07:35:00",
    title: "BRYAN MATTHEW MCGEHRIN - TANEYTOWN, MARYLAND",
    coordinates: [],
    hair_raw: "Brown",
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>Bryan McGehrin was last seen at his mother’s residence on October 25, 2019, in Taneytown, Maryland.  When he left her residence, he did not say where he was going.  He was released from jail in Hagerstown, Maryland, two days prior.  McGehrin does not have a cell phone but would historically make contact with his family using his friends’ phones.  McGehrin has depression and was not taking medication for it.  He was supposed to attend a probation meeting but missed it. If you have any information regarding this investigation, please contact the Westminster Police Department.</p>\r\n<p> </p>",
    status: "na",
    legat_names: null,
    eyes: "blue",
    person_classification: "Main",
    description: "October 25, 2019\r\nTaneytown, Maryland",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland/mcgehrin2.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland/mcgehrin2.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland/mcgehrin2.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland/mcgehrin3.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland/mcgehrin3.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland/mcgehrin3.jpg",
      },
    ],
    possible_countries: null,
    weight_min: 190,
    additional_information: null,
    remarks:
      "<p>McGehrin was last wearing gray sweatpants, a blue/gray hooded jacket, white tennis shoes, and a baseball cap.</p>",
    path: "/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland",
    eyes_raw: "Blue",
    weight_max: 190,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/vicap/missing-persons/bryan-matthew-mcgehrin---taneytown-maryland",
    possible_states: null,
    modified: "2025-01-21T00:05:20+00:00",
    reward_max: 0,
    race: "white",
    height_max: 68,
    place_of_birth: null,
    height_min: 68,
    poster_classification: "default",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/1584feee758e4cd39136171ef1c007f9",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson/download.pdf",
        name: "English",
      },
      {
        url: "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson/huyen-trang-temple-arson-spanish.pdf/@@download/file/huyen-trang-temple-arson.Spanish.pdf",
        name: "EN ESPAOL",
      },
    ],
    age_range: null,
    uid: "1b8be2fd26f348098f25f6d1e1f525fd",
    weight: null,
    occupations: null,
    field_offices: ["houston"],
    locations: null,
    reward_text:
      "The FBI is offering a reward of up to $10,000 for information leading to the identification, arrest, and conviction of the individual(s) responsible for the arson.",
    sex: null,
    hair: null,
    ncic: null,
    dates_of_birth_used: null,
    caution: null,
    nationality: null,
    age_min: null,
    age_max: null,
    scars_and_marks: null,
    subjects: ["Seeking Information"],
    aliases: null,
    race_raw: null,
    suspects: null,
    publication: "2024-01-12T13:55:00",
    title: "HUYEN TRANG TEMPLE - ARSON",
    coordinates: [],
    hair_raw: null,
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>On November 5, 2023, the Huyen Trang Temple located at 17505 FM 1485, New Caney, Texas, was vandalized by arson. At approximately 9:42 p.m., an unknown male suspect approached the temple and found an open window at the front of the temple. The unknown suspect then ignited the top of a gas-filled mason jar with fire and threw it into the temple, starting a fire in the main place of worship where a monk was asleep on the floor. The unknown suspect then fled the scene, and the monks that were sleeping in the temple extinguished the fire with no serious injuries.</p>\r\n<p> </p>",
    status: "na",
    legat_names: null,
    eyes: null,
    person_classification: "Main",
    description: "New Caney, Texas\r\nNovember 5, 2023",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson/unsub2.png/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson/unsub2.png/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson/unsub2.png",
      },
      {
        large:
          "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson/unsubboots.png/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson/unsubboots.png/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson/unsubboots.png",
      },
    ],
    possible_countries: null,
    weight_min: null,
    additional_information: null,
    remarks:
      "<p>The unknown suspect was wearing unique-colored boots, tactical pants, a baseball cap, and a gaiter covering his face.</p>",
    path: "/wanted/seeking-info/huyen-trang-temple-arson",
    eyes_raw: null,
    weight_max: null,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/seeking-info/huyen-trang-temple-arson",
    possible_states: null,
    modified: "2025-01-21T00:05:20+00:00",
    reward_max: 0,
    race: null,
    height_max: null,
    place_of_birth: null,
    height_min: null,
    poster_classification: "information",
    warning_message: "SHOULD BE CONSIDERED DANGEROUS",
    pathId:
      "https://api.fbi.gov/@wanted-person/1b8be2fd26f348098f25f6d1e1f525fd",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan/vicap-alert-2024-04-07.pdf",
        name: "English",
      },
    ],
    age_range: "21 years old at time of disappearance",
    uid: "4f5f62ea98c34547a11f12fd12e040ca",
    weight: "110 pounds",
    occupations: null,
    field_offices: null,
    locations: null,
    reward_text: null,
    sex: "Female",
    hair: "brown",
    ncic: null,
    dates_of_birth_used: null,
    caution: null,
    nationality: null,
    age_min: 21,
    age_max: 21,
    scars_and_marks: null,
    subjects: ["ViCAP Missing Persons"],
    aliases: null,
    race_raw: "White",
    suspects: null,
    publication: "2024-04-29T13:46:00",
    title: "IDA DEAN (RICHARDSON) ANDERSON - ANN ARBOR, MICHIGAN",
    coordinates: [],
    hair_raw: "Light Brown",
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>Ida Dean (Richardson) Anderson, a 21-year-old white female, was last seen on September 18, 1958, in Ann Arbor, Michigan. She was due in court the next day for her parental rights case and was to be awarded custody of her children, but due to conflicting court documents it is unclear if she showed up. Ida had left her husband in March 1958 and was hospitalized soon after for various illnesses. As a result, her estranged husband placed their children in a boarding home and moved to Chicago while Ida was in the hospital. The state of Michigan took custody of the children and Ida had been fighting to get them back since she was released. Arrangements had been made for Ida and her children to fly to Florida to visit family after the September 19, 1958, court date but she did not show. Prior to her disappearance, Ida remained in constant contact with her family via mail. Anyone with information regarding Ida’s disappearance is asked to contact the Ann Arbor Police Department.</p>",
    status: "na",
    legat_names: null,
    eyes: "green",
    person_classification: "Main",
    description: "September 18, 1958\r\nAnn Arbor, Michigan",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan/@@images/image/large",
        caption: "Photograph taken between 1956 and 1958",
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan/ida_anderson2.jpg/@@images/image/large",
        caption: "Photograph taken between 1956 and 1958",
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan/ida_anderson2.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan/ida_anderson2.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan/ida_anderson3.jpg/@@images/image/large",
        caption: "Photograph taken between 1956 and 1958",
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan/ida_anderson3.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan/ida_anderson3.jpg",
      },
    ],
    possible_countries: null,
    weight_min: 110,
    additional_information: null,
    remarks:
      "<p>Ida Dean (Richardson) Anderson usually wore dresses, long skirts, and button-up shirts. </p>",
    path: "/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan",
    eyes_raw: "Green",
    weight_max: 110,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/vicap/missing-persons/ida-dean-richardson-anderson---ann-arbor-michigan",
    possible_states: null,
    modified: "2025-01-21T00:05:20+00:00",
    reward_max: 0,
    race: "white",
    height_max: 62,
    place_of_birth: null,
    height_min: 62,
    poster_classification: "default",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/4f5f62ea98c34547a11f12fd12e040ca",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/kidnap/elsie-eldora-luscier/download.pdf",
        name: "English",
      },
    ],
    age_range: null,
    uid: "fca89f1133a74259b4a0f944cd238343",
    weight: "110 pounds (at time of disappearance)",
    occupations: null,
    field_offices: ["seattle"],
    locations: null,
    reward_text:
      "The FBI is offering a reward of up to $5,000 for information leading to the recovery of Elsie Eldora Luscier and the conviction of those responsible for her disappearance.",
    sex: "Female",
    hair: "brown",
    ncic: null,
    dates_of_birth_used: ["January 30, 1966"],
    caution: null,
    nationality: null,
    age_min: null,
    age_max: null,
    scars_and_marks: null,
    subjects: ["Kidnappings and Missing Persons", "Indian Country"],
    aliases: null,
    race_raw: null,
    suspects: null,
    publication: "2023-08-25T08:05:00",
    title: "ELSIE ELDORA LUSCIER",
    coordinates: [],
    hair_raw: "Brown",
    languages: null,
    complexion: null,
    build: null,
    details:
      '<p>On August 30, 1979, Elsie Eldora Luscier, accompanied by her cousin, <a data-urltype="/view" data-val="https://www.fbi.gov/wanted/kidnap/carlotta-maria-sanchez" href="https://www.fbi.gov/wanted/kidnap/carlotta-maria-sanchez" data-linktype="external">Carlotta Maria Sanchez</a>, disappeared from Taholah, Washington, which is in the Quinault Nation Indian Reservation.  The FBI is seeking information about the disappearance of both girls, and about those responsible for their disappearance.</p>\r\n<p> </p>',
    status: "na",
    legat_names: null,
    eyes: "brown",
    person_classification: "Main",
    description: "August 30, 1979\r\nTaholah, Washington",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/kidnap/elsie-eldora-luscier/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/kidnap/elsie-eldora-luscier/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/kidnap/elsie-eldora-luscier/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/kidnap/elsie-eldora-luscier/luscier2.jpg/@@images/image/large",
        caption: "Enhanced Image",
        thumb:
          "https://www.fbi.gov/wanted/kidnap/elsie-eldora-luscier/luscier2.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/kidnap/elsie-eldora-luscier/luscier2.jpg",
      },
    ],
    possible_countries: null,
    weight_min: 110,
    additional_information: null,
    remarks: null,
    path: "/wanted/kidnap/elsie-eldora-luscier",
    eyes_raw: "Brown",
    weight_max: 110,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/kidnap/elsie-eldora-luscier",
    possible_states: null,
    modified: "2025-01-21T00:05:19+00:00",
    reward_max: 0,
    race: null,
    height_max: 61,
    place_of_birth: null,
    height_min: 61,
    poster_classification: "missing",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/fca89f1133a74259b4a0f944cd238343",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/vicap/missing-persons/mitchell-todd-hein/vicap-alert-mitchell-hein-12-1-2020.pdf",
        name: "English",
      },
    ],
    age_range: "Approximately 22 years old",
    uid: "b241a3d5007b4abcba4a085ea95831a1",
    weight: "Approximately 170 pounds",
    occupations: null,
    field_offices: null,
    locations: null,
    reward_text: null,
    sex: "Male",
    hair: "brown",
    ncic: null,
    dates_of_birth_used: null,
    caution: null,
    nationality: null,
    age_min: 22,
    age_max: 22,
    scars_and_marks:
      "The victim had a major scar on his knee and a full beard when last seen.",
    subjects: ["ViCAP Missing Persons"],
    aliases: null,
    race_raw: "White",
    suspects: null,
    publication: "2020-12-10T13:40:00",
    title: "MITCHELL TODD HEIN - INDIO, CALIFORNIA",
    coordinates: [],
    hair_raw: "Brown/auburn and naturally curly",
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>Jefferson County Sheriff’s Office in Colorado is seeking assistance from the public to locate Mitchell Todd Hein. Hein visited family in Jefferson County, Colorado, in December of 1982 and abruptly left in January or February of 1983 without saying goodbye to anyone. He was carrying his clothes and belongings in a black trash bag. According to a friend, Hein showed up in Clinton, Oklahoma, and then in early March 1983, Hein hitched a ride with the friend's father to California. They stopped for the night in Indio, California. Hein left the hotel room and has not been seen or heard from since. It was reported that Hein had thrown away his driver's license and social security card and may have had no form of identification on him.</p>",
    status: "na",
    legat_names: null,
    eyes: "brown",
    person_classification: "Main",
    description: "Indio, California\r\nFebruary 1, 1983",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/mitchell-todd-hein/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/mitchell-todd-hein/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/mitchell-todd-hein/@@images/image",
      },
    ],
    possible_countries: null,
    weight_min: 170,
    additional_information: null,
    remarks:
      "<p>Clothing included the following: Tattered blue jeans; a flannel shirt; and either tennis shoes or work boots.</p>",
    path: "/wanted/vicap/missing-persons/mitchell-todd-hein",
    eyes_raw: "Brown",
    weight_max: 170,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/vicap/missing-persons/mitchell-todd-hein",
    possible_states: null,
    modified: "2025-01-21T00:05:19+00:00",
    reward_max: 0,
    race: "white",
    height_max: 72,
    place_of_birth: null,
    height_min: 70,
    poster_classification: "missing",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/b241a3d5007b4abcba4a085ea95831a1",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/vicap/missing-persons/atraya-berardi-rockledge-florida/vicapalert-2024-07-13atraya-berardi.pdf",
        name: "English",
      },
    ],
    age_range: "16 years old (at the time of disappearance)",
    uid: "bf729b6c730241e4a94a952c5a04b42b",
    weight: "110 pounds",
    occupations: null,
    field_offices: null,
    locations: null,
    reward_text: null,
    sex: "Female",
    hair: "brown",
    ncic: null,
    dates_of_birth_used: null,
    caution: null,
    nationality: null,
    age_min: 16,
    age_max: 16,
    scars_and_marks:
      "She has a tattoo of a heart between left finger and thumb.",
    subjects: [],
    aliases: null,
    race_raw: "White",
    suspects: null,
    publication: "2024-07-26T12:47:00",
    title: "ATRAYA BERARDI - ROCKLEDGE, FLORIDA",
    coordinates: [],
    hair_raw: "Brown",
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>Atraya Berardi was last seen on May 24, 2024, at 23:00 hours, leaving her residence where she lived with her aunt and uncle in Rockledge, Floridda, since March 2024. Prior to that, Berardi lived in Palatka, Florida, with her mother until January 2024, when her mother passed away. Berardi has no other ties to Rockledge. Berardi left behind her cellular phone, laptop, and most of her personal belongings. She left with her gray cat, that has a deformed ear, in a pet carrier and a bag of toiletries. Berardi has a history of running away in Palatka; however, she always returns after a couple days. The Rockledge Police Department is asking for assistance in locating Berardi or providing details of her disappearance.</p>",
    status: "na",
    legat_names: null,
    eyes: "brown",
    person_classification: "Main",
    description: "May 24, 2024\r\nRockledge, Florida",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/atraya-berardi-rockledge-florida/@@images/image/large",
        caption: "Photograph taken May 2024",
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/atraya-berardi-rockledge-florida/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/atraya-berardi-rockledge-florida/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/atraya-berardi-rockledge-florida/berardi1.png/@@images/image/large",
        caption: "Photograph taken May 2024",
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/atraya-berardi-rockledge-florida/berardi1.png/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/atraya-berardi-rockledge-florida/berardi1.png",
      },
    ],
    possible_countries: null,
    weight_min: 110,
    additional_information: null,
    remarks: null,
    path: "/wanted/vicap/missing-persons/atraya-berardi-rockledge-florida",
    eyes_raw: "Brown",
    weight_max: 110,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/vicap/missing-persons/atraya-berardi-rockledge-florida",
    possible_states: null,
    modified: "2025-01-21T00:05:19+00:00",
    reward_max: 0,
    race: "white",
    height_max: 64,
    place_of_birth: null,
    height_min: 64,
    poster_classification: "default",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/bf729b6c730241e4a94a952c5a04b42b",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/vicap/unidentified-persons/john-doe---waterloo-township-michigan/alert-unidentified_human_remains-waterloo-township-mi.pdf",
        name: "English",
      },
    ],
    age_range: "20 to 45 years old",
    uid: "7d60ad83779047dd95914d0d1bf79e11",
    weight: "114 to 145 pounds",
    occupations: null,
    field_offices: null,
    locations: null,
    reward_text: null,
    sex: "Male",
    hair: "black",
    ncic: null,
    dates_of_birth_used: null,
    caution: null,
    nationality: null,
    age_min: 20,
    age_max: 45,
    scars_and_marks: null,
    subjects: ["ViCAP Unidentified Persons"],
    aliases: null,
    race_raw: "Black",
    suspects: null,
    publication: "2021-02-23T11:33:00",
    title: "JOHN DOE - WATERLOO TOWNSHIP, MICHIGAN",
    coordinates: [],
    hair_raw: "Black (natural), auburn wavy collar length wig",
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>On Wednesday, August 30, 1978, the skeletal remains of a black male dressed in women’s clothing and a wig were found bound and wrapped in plastic trash bags. The male had a right shoulder surgical implantation of two large staples into the lateral aspect of greater tubercle of the right humerus and a 32 mm (1 ¼”) screw into the anterior border of glenoid fossa of the right scapula. He was missing 10 teeth to include his two upper front teeth and there was evidence of a healed nasal fracture. The cause of death could not be determined; however, based on how the body was found this case is considered a homicide. The Michigan State Police (MSP) Violent Crimes Unit (VCU) is requesting assistance with identifying this male and any similar cases.</p>",
    status: "na",
    legat_names: null,
    eyes: null,
    person_classification: "Main",
    description: "August 30, 1978 \r\nWaterloo Township, Michigan",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/vicap/unidentified-persons/john-doe---waterloo-township-michigan/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/vicap/unidentified-persons/john-doe---waterloo-township-michigan/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/unidentified-persons/john-doe---waterloo-township-michigan/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/vicap/unidentified-persons/john-doe---waterloo-township-michigan/thumbnail_-waterloo-township-mi-2.png/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/vicap/unidentified-persons/john-doe---waterloo-township-michigan/thumbnail_-waterloo-township-mi-2.png/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/unidentified-persons/john-doe---waterloo-township-michigan/thumbnail_-waterloo-township-mi-2.png",
      },
    ],
    possible_countries: null,
    weight_min: 114,
    additional_information: null,
    remarks:
      '<p>Unknown Distinguishing Characteristics: May have had a sizable scar on right shoulder from surgical intervention. Missing 10 teeth including the two upper front teeth. Evidence of a healed nasal fracture.</p>\r\n<p>Clothing/Belongings: Blue jeans (size 26 waist, 33 ½” inseam); violet long-sleeve blouse (size 14, 100% silk, label "IRKA"); beige long-sleeve blouse (size 5/6, 100% polyester, label "RD2"); reddish brown nylon neck scarf; panty hose; bra (size 34); bikini panty (size 4); glossy black high heeled shoes (4 1/2 inch) with gold tassel ankle tie; gold bracelet.</p>',
    path: "/wanted/vicap/unidentified-persons/john-doe---waterloo-township-michigan",
    eyes_raw: null,
    weight_max: 145,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/vicap/unidentified-persons/john-doe---waterloo-township-michigan",
    possible_states: null,
    modified: "2025-01-21T00:05:19+00:00",
    reward_max: 0,
    race: "black",
    height_max: 69,
    place_of_birth: null,
    height_min: 62,
    poster_classification: "information",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/7d60ad83779047dd95914d0d1bf79e11",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/seeking-info/dhulfiqar-kareem-mseer/download.pdf",
        name: "English",
      },
    ],
    age_range: null,
    uid: "8a3744a5b3224886a0affe5df455a4c0",
    weight: null,
    occupations: null,
    field_offices: ["portland"],
    locations: null,
    reward_text:
      "The FBI is offering a reward of up to $15,000 for information leading to the arrest and conviction of the individual(s) responsible for the murder of Dhulfiqar Kareem Mseer.",
    sex: null,
    hair: null,
    ncic: null,
    dates_of_birth_used: null,
    caution: null,
    nationality: null,
    age_min: null,
    age_max: null,
    scars_and_marks: null,
    subjects: ["Seeking Information"],
    aliases: null,
    race_raw: null,
    suspects: null,
    publication: "2021-10-18T08:07:00",
    title: "DHULFIQAR KAREEM MSEER",
    coordinates: [],
    hair_raw: null,
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>On December 11, 2020, 23-year-old Dhulfiqar Kareem Mseer was working as an Uber driver.  Shortly before midnight, he arrived in the area of NE Stafford Street and NE 11th Avenue in Portland, Oregon, to pick up a fare.  He was shot by multiple subjects who fired approximately 70 rounds.  He died several days later.  The subjects got into two cars before leaving the area.  One of the cars is believed to be a VW Eos.  Shell casings recovered at the scene have been matched to casings found at other gang-involved shootings in the area.</p>\r\n<p> </p>",
    status: "na",
    legat_names: null,
    eyes: null,
    person_classification: "Main",
    description: "Homicide Victim\r\nPortland, Oregon\r\nDecember 11, 2020",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/seeking-info/dhulfiqar-kareem-mseer/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/seeking-info/dhulfiqar-kareem-mseer/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/seeking-info/dhulfiqar-kareem-mseer/@@images/image",
      },
    ],
    possible_countries: null,
    weight_min: null,
    additional_information: null,
    remarks: null,
    path: "/wanted/seeking-info/dhulfiqar-kareem-mseer",
    eyes_raw: null,
    weight_max: null,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/seeking-info/dhulfiqar-kareem-mseer",
    possible_states: null,
    modified: "2025-01-21T00:05:18+00:00",
    reward_max: 0,
    race: null,
    height_max: null,
    place_of_birth: null,
    height_min: null,
    poster_classification: "information",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/8a3744a5b3224886a0affe5df455a4c0",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/download.pdf",
        name: "English",
      },
    ],
    age_range: null,
    uid: "36715efc74c94930a5cc5e30d52ab0f8",
    weight: null,
    occupations: null,
    field_offices: ["honolulu"],
    locations: null,
    reward_text: null,
    sex: "Male",
    hair: null,
    ncic: null,
    dates_of_birth_used: ["January 23, 2013"],
    caution: null,
    nationality: null,
    age_min: null,
    age_max: null,
    scars_and_marks: null,
    subjects: ["Kidnappings and Missing Persons"],
    aliases: ["Eliav"],
    race_raw: null,
    suspects: null,
    publication: "2024-06-28T14:49:00",
    title: "KOA KAI BERNSTEIN",
    coordinates: [],
    hair_raw: null,
    languages: null,
    complexion: null,
    build: null,
    details:
      '<p>The Federal Bureau of Investigation in Honolulu is seeking information regarding <a data-urltype="/view" data-val="https://www.fbi.gov/wanted/kidnap/abigail-bernstein" href="https://www.fbi.gov/wanted/kidnap/abigail-bernstein" data-linktype="external">Abigail Bernstein</a> and her two children, Koa Kai Bernstein and <a data-urltype="/view" data-val="https://www.fbi.gov/wanted/kidnap/kush-kohole-bernstein" href="https://www.fbi.gov/wanted/kidnap/kush-kohole-bernstein" data-linktype="external">Kush Kohole Bernstein</a>.  The family was last seen at Ala Wai Boat Harbor in Honolulu, Hawaii, in October of 2022. </p>\r\n<p> </p>',
    status: "na",
    legat_names: null,
    eyes: null,
    person_classification: "Main",
    description: "October of 2022\r\nAla Wai Boat Harbor\r\nHonolulu, Hawaii",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/@@images/image/large",
        caption: "Photograph taken in 2022",
        thumb:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinkai2022a.jpg/@@images/image/large",
        caption: "Photograph taken in 2022",
        thumb:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinkai2022a.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinkai2022a.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinfamily2021.jpg/@@images/image/large",
        caption: "Bernstein Family - Photograph taken in 2021",
        thumb:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinfamily2021.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinfamily2021.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinfamily1.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinfamily1.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinfamily1.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinkai2022b.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinkai2022b.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein/bernsteinkai2022b.jpg",
      },
    ],
    possible_countries: null,
    weight_min: null,
    additional_information: null,
    remarks:
      "<p>The Bernstein family has ties to Naples, Florida; Petoskey, Michigan; Lancaster, Pennsylvania; and Hawaii.</p>",
    path: "/wanted/kidnap/koa-kai-bernstein",
    eyes_raw: null,
    weight_max: null,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/kidnap/koa-kai-bernstein",
    possible_states: null,
    modified: "2025-01-21T00:05:18+00:00",
    reward_max: 0,
    race: null,
    height_max: null,
    place_of_birth: null,
    height_min: null,
    poster_classification: "missing",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/36715efc74c94930a5cc5e30d52ab0f8",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/cei/rodolfo-mantilla/download.pdf",
        name: "English",
      },
      {
        url: "https://www.fbi.gov/wanted/cei/rodolfo-mantilla/mantilla-spanish-final.pdf/@@download/file/Mantilla.Spanish.final.pdf",
        name: "EN ESPAOL",
      },
    ],
    age_range: null,
    uid: "63317cf0ccc44bb8a3f4bf834e2231f9",
    weight: null,
    occupations: null,
    field_offices: ["miami"],
    locations: null,
    reward_text:
      "The FBI is offering a reward of up to $10,000 for information leading to the arrest and conviction of Rodolfo Mantilla.",
    sex: "Male",
    hair: "black",
    ncic: null,
    dates_of_birth_used: ["February 27, 1981"],
    caution:
      "<p>Rodolfo Mantilla is wanted for allegedly importing bulk kilogram quantities of cocaine into the United States, specifically South Florida. It is alleged that the narcotics are then provided to distributors who sell the drugs for Mantilla, and provide him the cash. </p>\r\n<p> </p>\r\n<p>On April 11, 2024, a federal arrest warrant was issued for Mantilla in the United States District Court for the Southern District of Florida, Ft. Lauderdale, Florida, after he was charged with Conspiracy to Possess with Intent to Distribute Controlled Substances; Possession with Intent to Distribute Controlled Substances; and Distribution of a Controlled Substance.</p>",
    nationality: null,
    age_min: null,
    age_max: null,
    scars_and_marks: null,
    subjects: ["Criminal Enterprise Investigations"],
    aliases: ['"Rudy"'],
    race_raw: "White (Hispanic)",
    suspects: null,
    publication: "2024-07-16T09:06:00",
    title: "RODOLFO MANTILLA",
    coordinates: [],
    hair_raw: "Black",
    languages: ["English", "Spanish"],
    complexion: null,
    build: null,
    details: null,
    status: "na",
    legat_names: null,
    eyes: "brown",
    person_classification: "Main",
    description:
      "Conspiracy to Possess with Intent to Distribute Controlled Substances; Possession with Intent to Distribute Controlled Substances; Distribution of a Controlled Substance",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/cei/rodolfo-mantilla/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/cei/rodolfo-mantilla/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/cei/rodolfo-mantilla/@@images/image",
      },
    ],
    possible_countries: null,
    weight_min: null,
    additional_information: null,
    remarks:
      "<p>Mantilla has ties to or may visit the Dominican Republic and the Bahamas.</p>",
    path: "/wanted/cei/rodolfo-mantilla",
    eyes_raw: "Brown",
    weight_max: null,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/cei/rodolfo-mantilla",
    possible_states: null,
    modified: "2025-01-21T00:05:18+00:00",
    reward_max: 0,
    race: "hispanic",
    height_max: 69,
    place_of_birth: "Florida",
    height_min: 69,
    poster_classification: "default",
    warning_message: "SHOULD BE CONSIDERED AN ESCAPE RISK",
    pathId:
      "https://api.fbi.gov/@wanted-person/63317cf0ccc44bb8a3f4bf834e2231f9",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/vicap/missing-persons/randy-stewart-doran---new-orleans-louisiana/vicap-alert-2021-06-07-doran-1.pdf",
        name: "English",
      },
    ],
    age_range: "22 (at time of disappearance)",
    uid: "8774527c934e485297718c705533307a",
    weight: "160 pounds",
    occupations: null,
    field_offices: null,
    locations: null,
    reward_text: null,
    sex: "Male",
    hair: "brown",
    ncic: null,
    dates_of_birth_used: null,
    caution: null,
    nationality: null,
    age_min: 22,
    age_max: 22,
    scars_and_marks:
      "Doran has a scar on his upper lip.  He also has an extra vertebrae in his spine.",
    subjects: ["ViCAP Missing Persons"],
    aliases: null,
    race_raw: "White",
    suspects: null,
    publication: "2021-06-24T08:53:00",
    title: "RANDY STEWART DORAN - NEW ORLEANS, LOUISIANA",
    coordinates: [],
    hair_raw: "Brown, Collar Length",
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>Randy Stewart Doran left his family’s Los Angeles, California, residence in early 1978. His last communication with family members was in early April 1978 when he called an aunt, stating he was working on a shipping dock (possibly on the SS President riverboat) in New Orleans, Louisiana. Prior to his disappearance, he sent a postcard to his aunt from New Orleans saying he was doing fine. He has never been heard from again.</p>\r\n<p> </p>\r\n<p>Doran was known to hitchhike, traveling across the country from California to Florida. He was a U.S. Marine Corps veteran, an avid guitar player, and liked to write short stories and poetry. He also carried a small pocket Bible with him. Fingerprints are available for comparison, and DNA from family members is in CODIS.</p>\r\n<p> </p>",
    status: "na",
    legat_names: null,
    eyes: "blue",
    person_classification: "Main",
    description: "April 1, 1978\r\nNew Orleans, Louisiana",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/randy-stewart-doran---new-orleans-louisiana/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/randy-stewart-doran---new-orleans-louisiana/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/randy-stewart-doran---new-orleans-louisiana/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/randy-stewart-doran---new-orleans-louisiana/doran2.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/randy-stewart-doran---new-orleans-louisiana/doran2.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/randy-stewart-doran---new-orleans-louisiana/doran2.jpg",
      },
    ],
    possible_countries: null,
    weight_min: 160,
    additional_information: null,
    remarks: null,
    path: "/wanted/vicap/missing-persons/randy-stewart-doran---new-orleans-louisiana",
    eyes_raw: "Blue /Hazel",
    weight_max: 160,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/vicap/missing-persons/randy-stewart-doran---new-orleans-louisiana",
    possible_states: null,
    modified: "2025-01-21T00:05:18+00:00",
    reward_max: 0,
    race: "white",
    height_max: 71,
    place_of_birth: null,
    height_min: 71,
    poster_classification: "default",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/8774527c934e485297718c705533307a",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/cei/darasy-s-chhim/download.pdf",
        name: "English",
      },
    ],
    age_range: null,
    uid: "454ca0b04a3e402a83b86dfead65cbf2",
    weight: "180 to 190 pounds",
    occupations: null,
    field_offices: ["boston"],
    locations: null,
    reward_text:
      "The FBI is offering a reward of up to $10,000 to anyone with information leading to the location, arrest, and conviction of Darasy S. Chhim.",
    sex: "Male",
    hair: "black",
    ncic: null,
    dates_of_birth_used: ["August 13, 1985"],
    caution:
      "<p>The Federal Bureau of Investigation, Boston Division’s Merrimack Valley Transnational Organized Crime Task Force, and the Lowell Police Department are asking for the public’s assistance in locating Darasy S. Chhim, a member of the Lowell, Massachusetts-based gang One Family Clique (OFC), and the Bloods.  Chhim is wanted for his alleged role in a large-scale and long-running drug trafficking conspiracy in which 15 alleged gang members and associates were charged.  Chhim is the only remaining fugitive.  A federal arrest warrant was issued for Chhim on June 9, 2021, in the United States District Court, District of Massachusetts, Boston, Massachusetts, after he was charged with Conspiracy to Distribute and to Possess with Intent to Distribute Heroin, 500 Grams or More of Cocaine, Cocaine Base, 40 Grams or More of Fentanyl, 500 Grams or More of Methamphetamine, and MDMA.</p>\r\n<p> </p>",
    nationality: "American",
    age_min: null,
    age_max: null,
    scars_and_marks:
      'Chhim has a mole between his eyebrows, closer to the left. He also has the following tattoos: "Liliana Chhim" in cursive on his chest, “Hate Me Now & F*** The World" on his upper back, and a skull, roses, cards, and a hand sign on his right arm/shoulder.',
    subjects: ["Criminal Enterprise Investigations"],
    aliases: [
      "“Mystickal”",
      '"Mystikal"',
      '“Rizzus"',
      '"Russel"',
      '"Crusty Rusty"',
    ],
    race_raw: "Asian",
    suspects: null,
    publication: "2021-11-02T07:42:00",
    title: "DARASY S. CHHIM",
    coordinates: [],
    hair_raw: "Black",
    languages: null,
    complexion: null,
    build: null,
    details: null,
    status: "captured",
    legat_names: null,
    eyes: "brown",
    person_classification: "Main",
    description:
      "Conspiracy to Distribute and to Possess with Intent to Distribute Heroin, 500 Grams or More of Cocaine, Cocaine Base, 40 Grams or More of Fentanyl, 500 Grams or More of Methamphetamine, and MDMA",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim2.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim2.jpg/@@images/image/thumb",
        original: "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim2.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim3.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim3.jpg/@@images/image/thumb",
        original: "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim3.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim2021.jpg/@@images/image/large",
        caption: "Photograph taken in 2021",
        thumb:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim2021.jpg/@@images/image/thumb",
        original: "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim2021.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim4.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim4.jpg/@@images/image/thumb",
        original: "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim4.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim5.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim5.jpg/@@images/image/thumb",
        original: "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim5.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim6.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim6.jpg/@@images/image/thumb",
        original: "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim6.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim7.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim7.jpg/@@images/image/thumb",
        original: "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim7.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim8.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim8.jpg/@@images/image/thumb",
        original: "https://www.fbi.gov/wanted/cei/darasy-s-chhim/chhim8.jpg",
      },
    ],
    possible_countries: null,
    weight_min: 180,
    additional_information: null,
    remarks:
      "<p>Chhim speaks English and Khmer.  He is of Cambodian descent.  It is believed Chhim grew up in Revere and Lynn, Massachusetts, but it is unclear if he still has any ties there. Chhim has historical gang ties to both Lowell, Massachusetts, and Philadelphia, Pennsylvania, and he has family in Lowell and Tyngsboro, Massachusetts.</p>",
    path: "/wanted/cei/darasy-s-chhim",
    eyes_raw: "Brown",
    weight_max: 190,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/cei/darasy-s-chhim",
    possible_states: null,
    modified: "2025-01-21T00:05:17+00:00",
    reward_max: 0,
    race: "asian",
    height_max: 69,
    place_of_birth: "California",
    height_min: 69,
    poster_classification: "default",
    warning_message: "SHOULD BE CONSIDERED ARMED AND DANGEROUS",
    pathId:
      "https://api.fbi.gov/@wanted-person/454ca0b04a3e402a83b86dfead65cbf2",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/vicap/missing-persons/james-s-ruland---north-fond-du-lac-wisconsin/vicap-alert-2021-02-05-missing_person-2021-02-05-james-s-ruland-master-1.pdf",
        name: "English",
      },
    ],
    age_range: "Forty years old",
    uid: "b4db60d7ed14449cb73ba39564ef9e19",
    weight: "160 pounds",
    occupations: null,
    field_offices: null,
    locations: null,
    reward_text: null,
    sex: "Male",
    hair: "brown",
    ncic: null,
    dates_of_birth_used: null,
    caution: null,
    nationality: null,
    age_min: null,
    age_max: null,
    scars_and_marks: null,
    subjects: ["ViCAP Missing Persons"],
    aliases: null,
    race_raw: "White",
    suspects: null,
    publication: "2021-02-23T08:02:00",
    title: "JAMES S. RULAND - NORTH FOND du LAC, WISCONSIN",
    coordinates: [],
    hair_raw: "Brown, collar length",
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>On Thursday, October 26, 1995, James S. Ruland was last seen hitchhiking in North Fond du Lac, Wisconsin. Nine days later, he was reported missing by his sister. On November 14, 1995, Ruland’s white Dodge Aires station wagon was recovered from the Stretch Truck Stop near North Fond du Lac. The keys were in the ignition and Ruland’s personal possessions were in the cargo area.</p>\r\n<p>Ruland sustained a severe head injury when he was young which required a shunt implant. The initial shunt failed, necessitating a second shunt. The implants required “bilateral burr holes” so the shunts could pass through his skull. Fond du Lac Sheriff’s Office is requesting assistance with locating Ruland.</p>",
    status: "na",
    legat_names: null,
    eyes: "blue",
    person_classification: "Main",
    description: "October 26, 1995\r\nNorth Fond du Lac, Wisconsin",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/vicap/missing-persons/james-s-ruland---north-fond-du-lac-wisconsin/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/vicap/missing-persons/james-s-ruland---north-fond-du-lac-wisconsin/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/vicap/missing-persons/james-s-ruland---north-fond-du-lac-wisconsin/@@images/image",
      },
    ],
    possible_countries: null,
    weight_min: 160,
    additional_information: null,
    remarks:
      "<p>Distinguishing Characteristics: Metal plate in head - bilateral burr holes/shunts, mustache</p>\r\n<p>Clothing/Belongings: Green camouflage jacket, silver wire rimmed glasses</p>",
    path: "/wanted/vicap/missing-persons/james-s-ruland---north-fond-du-lac-wisconsin",
    eyes_raw: "Blue, wears glasses",
    weight_max: 160,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/vicap/missing-persons/james-s-ruland---north-fond-du-lac-wisconsin",
    possible_states: null,
    modified: "2025-01-21T00:05:17+00:00",
    reward_max: 0,
    race: "white",
    height_max: 72,
    place_of_birth: null,
    height_min: 72,
    poster_classification: "missing",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/b4db60d7ed14449cb73ba39564ef9e19",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/kidnap/mary-johnson-davis/download.pdf",
        name: "English",
      },
    ],
    age_range: null,
    uid: "d68267f4793d4ed1a27d4f51685865c3",
    weight: "115 pounds",
    occupations: null,
    field_offices: ["seattle"],
    locations: null,
    reward_text:
      "The FBI is offering a reward of up to $10,000 for information leading to the identification, arrest, and conviction of person(s) responsible for the disappearance of Mary Johnson (Davis).",
    sex: "Female",
    hair: "black",
    ncic: null,
    dates_of_birth_used: ["August 31, 1981"],
    caution: null,
    nationality: "American",
    age_min: null,
    age_max: null,
    scars_and_marks: "Mary has a Sunburst-type tattoo on her upper right arm.",
    subjects: ["Kidnappings and Missing Persons", "Indian Country"],
    aliases: ["Mary E. Davis", "Mary E. Johnson"],
    race_raw: "Native American/Alaskan Native",
    suspects: null,
    publication: "2021-09-14T06:37:00",
    title: "MARY JOHNSON (DAVIS)",
    coordinates: [],
    hair_raw: "Black",
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>The Federal Bureau of Investigation's Seattle Field Office and the Tulalip Tribal Police are investigating the disappearance of Mary Johnson (Davis), last seen November 25, 2020, walking east on Firetrail Road on the Tulalip Reservation in Washington State.  Mary was traveling to a friend’s house and never arrived.  She was reported missing December 9, 2020. </p>\r\n<p> </p>",
    status: "na",
    legat_names: null,
    eyes: "brown",
    person_classification: "Main",
    description: "November 25, 2020\r\nTulalip Reservation\r\nWashington State",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/kidnap/mary-johnson-davis/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/kidnap/mary-johnson-davis/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/kidnap/mary-johnson-davis/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/kidnap/mary-johnson-davis/johnson2.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/kidnap/mary-johnson-davis/johnson2.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/kidnap/mary-johnson-davis/johnson2.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/kidnap/mary-johnson-davis/johnson3.jpg/@@images/image/large",
        caption: "",
        thumb:
          "https://www.fbi.gov/wanted/kidnap/mary-johnson-davis/johnson3.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/kidnap/mary-johnson-davis/johnson3.jpg",
      },
    ],
    possible_countries: null,
    weight_min: 115,
    additional_information: null,
    remarks: null,
    path: "/wanted/kidnap/mary-johnson-davis",
    eyes_raw: "Brown",
    weight_max: 115,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/kidnap/mary-johnson-davis",
    possible_states: null,
    modified: "2025-01-21T00:05:17+00:00",
    reward_max: 0,
    race: "native",
    height_max: 66,
    place_of_birth: "Washington State",
    height_min: 66,
    poster_classification: "missing",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/d68267f4793d4ed1a27d4f51685865c3",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/wcc/frederick-arias/download.pdf",
        name: "English",
      },
      {
        url: "https://www.fbi.gov/wanted/wcc/frederick-arias/arias-norwegian-8-18-2020.pdf/@@download/file/Arias Norwegian 8-18-2020.pdf",
        name: "P NORSK",
      },
      {
        url: "https://www.fbi.gov/wanted/wcc/frederick-arias/arias-czech-8-19-2020.pdf/@@download/file/Arias Czech 8-19-2020.pdf",
        name: "V ETIN",
      },
      {
        url: "https://www.fbi.gov/wanted/wcc/frederick-arias/arias-spanish-9-15-2020.pdf/@@download/file/Arias Spanish 9-15-2020.pdf",
        name: "EN ESPAOL",
      },
    ],
    age_range: null,
    uid: "8ff4f4c1329a40c686d8f553062c2996",
    weight: "209 to 210 pounds",
    occupations: null,
    field_offices: ["phoenix"],
    locations: null,
    reward_text:
      "The FBI is offering a reward of up to $25,000 for information leading to the arrest and conviction of Frederick Arias.",
    sex: "Male",
    hair: "brown",
    ncic: null,
    dates_of_birth_used: ["September 13, 1966"],
    caution:
      "<p>Frederick Arias is wanted for his alleged involvement in a fraud scheme in which victim investors lost over $9 million dollars.</p>\r\n<p>Between December of 2015 and October of 2017, Arias allegedly told investors that The Joseph Project was a safe and secure investment with guaranteed profits. Instead, Arias allegedly withdrew funds to pay personal expenses and wired funds overseas.</p>\r\n<p>On June 6, 2019, Arias was charged with conspiracy; fraudulent schemes and artifices; money laundering in the first degree; ten counts of theft; two counts of illegal control of an enterprise; forgery; and fraudulent schemes by the Superior Court of the State of Arizona in and for the County of Maricopa, and a warrant was issued for his arrest. On June 10, 2019, Arias was arrested in Kirkland, Washington. On June 13, 2019, Arias was released from custody on bond, and subsequently failed to appear for an extradition hearing. On June 17, 2019, Arias was indicted on the above 17 charges related to the fraud scheme. On June 26, 2019, the King County District Court in King County, Washington, charged Arias with failure to appear, and a warrant was issued for his arrest. On March 19, 2020, Arias was charged federally with unlawful flight to avoid prosecution in the United States District Court for the District of Arizona, Phoenix, Arizona, and a warrant was issued for his arrest.</p>\r\n<p> </p>",
    nationality: "American",
    age_min: null,
    age_max: null,
    scars_and_marks: null,
    subjects: ["White-Collar Crime"],
    aliases: ["Fred Arias", "Frederick M. Arias"],
    race_raw: "White",
    suspects: null,
    publication: "2019-11-27T08:10:00",
    title: "FREDERICK ARIAS",
    coordinates: [],
    hair_raw: "Brown",
    languages: ["Spanish", "English"],
    complexion: null,
    build: null,
    details: null,
    status: "na",
    legat_names: null,
    eyes: "hazel",
    person_classification: "Main",
    description:
      "Unlawful Flight to Avoid Prosecution - Conspiracy; Fraudulent Schemes and Artifices; Money Laundering in the First Degree; Theft (10 Counts); Illegal Control of an Enterprise (Two Counts); Forgery; Fraudulent Schemes and Practices; Failure to Appear",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/wcc/frederick-arias/@@images/image/large",
        caption: "Photograph taken in 2019",
        thumb:
          "https://www.fbi.gov/wanted/wcc/frederick-arias/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/wcc/frederick-arias/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/wcc/frederick-arias/arias2009.png/@@images/image/large",
        caption: "Photograph taken in 2009",
        thumb:
          "https://www.fbi.gov/wanted/wcc/frederick-arias/arias2009.png/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/wcc/frederick-arias/arias2009.png",
      },
    ],
    possible_countries: null,
    weight_min: 209,
    additional_information: null,
    remarks:
      "<p>Arias has ties to, or may visit, Canada, Norway, Australia, the Czech Republic, and the Dominican Republic. He is a former law enforcement officer. Arias has previously resided in Kirkland, Washington.</p>",
    path: "/wanted/wcc/frederick-arias",
    eyes_raw: "Hazel",
    weight_max: 210,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/wcc/frederick-arias",
    possible_states: null,
    modified: "2025-01-21T00:05:17+00:00",
    reward_max: 0,
    race: "white",
    height_max: 70,
    place_of_birth: "New York",
    height_min: 68,
    poster_classification: "default",
    warning_message: "SHOULD BE CONSIDERED AN ESCAPE RISK",
    pathId:
      "https://api.fbi.gov/@wanted-person/8ff4f4c1329a40c686d8f553062c2996",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/download.pdf",
        name: "English",
      },
    ],
    age_range: null,
    uid: "5fa689c890b446f9958181d77e665767",
    weight: null,
    occupations: null,
    field_offices: ["portland", "seattle"],
    locations: null,
    reward_text:
      "The FBI is offering a reward of up to $25,000 for information leading to the identification, arrest, and conviction of the suspect responsible for these crimes.",
    sex: null,
    hair: null,
    ncic: null,
    dates_of_birth_used: null,
    caution: null,
    nationality: null,
    age_min: null,
    age_max: null,
    scars_and_marks: null,
    subjects: ["Seeking Information"],
    aliases: null,
    race_raw: null,
    suspects: null,
    publication: "2024-11-06T13:32:00",
    title: "BALLOT BOX FIRES",
    coordinates: [],
    hair_raw: null,
    languages: null,
    complexion: null,
    build: null,
    details:
      "<p>The FBI is seeking the public's assistance in identifying the unknown suspect involved in setting incendiary fires at two ballot boxes in Vancouver, Washington, and one in Portland, Oregon.  On October 8, 2024, between 3:30 and 4:00 a.m., an unknown individual placed an improvised incendiary device on a ballot drop box in Vancouver, Washington. Subsequently, on October 28, 2024, between 2:00 and 4:00 a.m., improvised incendiary devices were placed on ballot drop boxes in Vancouver, Washington, and Portland, Oregon.</p>\r\n<p> </p>\r\n<p>A surveillance camera captured images of an early 2003 to 2004 Volvo S-60 sedan, dark in color, with dark wheels and a light-colored interior, driven by the suspect believed to responsible for these crimes. The vehicle does not have a Volvo logo on the front grill.  At the time of the October 28, 2024, incidents, the vehicle also displayed a fraudulent temporary Washington license plate on the rear and no front license plate. The plate, which is not associated with a Volvo, may no longer be on the vehicle.</p>\r\n<p> </p>\r\n<p>The driver of the vehicle is described as a White male, approximately 30 to 40 years old with thinning hair. It is believed that he may have some experience with metal work and welding.</p>\r\n<p> </p>",
    status: "na",
    legat_names: null,
    eyes: null,
    person_classification: "Main",
    description: "Vancouver, Washington\r\nPortland, Oregon\r\nOctober 2024",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/@@images/image/large",
        caption: "Ballot Box and Suspect Car - Portland, Oregon",
        thumb:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/@@images/image",
      },
      {
        large:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/ballotbox1.jpg/@@images/image/large",
        caption: "Suspect Car",
        thumb:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/ballotbox1.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/ballotbox1.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/ballotbox2.jpg/@@images/image/large",
        caption: "Suspect Car",
        thumb:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/ballotbox2.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/ballotbox2.jpg",
      },
      {
        large:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/ballotboxpd.jpg/@@images/image/large",
        caption: "Ballot Box - Portland, Oregon",
        thumb:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/ballotboxpd.jpg/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires/ballotboxpd.jpg",
      },
    ],
    possible_countries: null,
    weight_min: null,
    additional_information: null,
    remarks: null,
    path: "/wanted/seeking-info/ballot-box-fires",
    eyes_raw: null,
    weight_max: null,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/seeking-info/ballot-box-fires",
    possible_states: null,
    modified: "2025-01-21T00:05:16+00:00",
    reward_max: 0,
    race: null,
    height_max: null,
    place_of_birth: null,
    height_min: null,
    poster_classification: "information",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/5fa689c890b446f9958181d77e665767",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/wcc/roscoe-mcmillan/download.pdf",
        name: "English",
      },
    ],
    age_range: null,
    uid: "023ab3979cb94f62a491635623bd4ed6",
    weight: "175 pounds",
    occupations: ["Nurse"],
    field_offices: ["atlanta"],
    locations: null,
    reward_text: null,
    sex: "Male",
    hair: "black",
    ncic: null,
    dates_of_birth_used: ["February 27, 1981"],
    caution:
      "<p>Roscoe McMillan is wanted for failing to appear for trial. In September 2023, McMillan was charged with wire fraud and mail fraud related to an alleged scheme to defraud seven life insurance companies. He was granted pre-trial release on October 11, 2023, and did not appear for his trial on the fraud charges on October 29, 2024. </p>\r\n<p> </p>\r\n<p>On November 5, 2024, a federal arrest warrant was issued for McMillan in the United States District Court, Northern District of Georgia, Atlanta, Georgia.</p>",
    nationality: "American",
    age_min: null,
    age_max: null,
    scars_and_marks: null,
    subjects: ["White Collar Crimes"],
    aliases: ["Roscoe McMillian", "Ross McMillan"],
    race_raw: "Black",
    suspects: null,
    publication: "2024-11-08T12:42:00",
    title: "ROSCOE MCMILLAN",
    coordinates: [],
    hair_raw: "Black",
    languages: null,
    complexion: null,
    build: null,
    details: null,
    status: "na",
    legat_names: null,
    eyes: "brown",
    person_classification: "Main",
    description: "Failure to Appear (Wire Fraud; Mail Fraud)",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/wcc/roscoe-mcmillan/@@images/image/large",
        caption: "Photograph taken in 2023",
        thumb:
          "https://www.fbi.gov/wanted/wcc/roscoe-mcmillan/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/wcc/roscoe-mcmillan/@@images/image",
      },
    ],
    possible_countries: null,
    weight_min: 175,
    additional_information: null,
    remarks:
      "<p>McMillan has ties to or may visit Las Vegas, Nevada; Atlanta, Georgia; South Carolina; and New York, New York.</p>",
    path: "/wanted/wcc/roscoe-mcmillan",
    eyes_raw: "Brown",
    weight_max: 175,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/wcc/roscoe-mcmillan",
    possible_states: null,
    modified: "2025-01-21T00:05:16+00:00",
    reward_max: 0,
    race: "black",
    height_max: 70,
    place_of_birth: "New York",
    height_min: 70,
    poster_classification: "default",
    warning_message: null,
    pathId:
      "https://api.fbi.gov/@wanted-person/023ab3979cb94f62a491635623bd4ed6",
  },
  {
    files: [
      {
        url: "https://www.fbi.gov/wanted/cei/edwin-ernesto-cedillos-rodriguez/download.pdf",
        name: "English",
      },
      {
        url: "https://www.fbi.gov/wanted/cei/edwin-ernesto-cedillos-rodriguez/cedillosrodriguezspanish.pdf/@@download/file/cedillosrodriguezSpanish.pdf",
        name: "EN ESPAOL",
      },
    ],
    age_range: null,
    uid: "cd626d1aedfd4acc816a1a3a418b1472",
    weight: null,
    occupations: null,
    field_offices: null,
    locations: null,
    reward_text: null,
    sex: "Male",
    hair: null,
    ncic: null,
    dates_of_birth_used: ["September 2, 1987"],
    caution:
      "<p>Edwin Ernesto Cedillos-Rodriguez is wanted for his alleged involvement in the direction of MS-13 activity in the United States, Mexico, and El Salvador.  He is alleged to be a senior leader of MS-13.  Cedillos-Rodriguez has been charged with several offenses for his alleged role in ordering numerous acts of violence against civilians and rival gang members, as well as his role in drug distribution and extortion schemes in the United States and El Salvador.  A federal arrest warrant was issued for Cedillos-Rodriguez in the United States District Court, Eastern District of New York, Central Islip, New York, on September 22, 2022, after he was charged with Conspiracy to Provide Material Support to Terrorists, Narco-Terrorism Conspiracy, and Racketeering Conspiracy.</p>\r\n<p> </p>\r\n<p>This case is being investigated as part of Joint Task Force Vulcan.</p>\r\n<p> </p>",
    nationality: "Salvadoran",
    age_min: null,
    age_max: null,
    scars_and_marks: null,
    subjects: ["Criminal Enterprise Investigations"],
    aliases: ['"Renuente de Abriles Dangers"'],
    race_raw: "White (Hispanic)",
    suspects: null,
    publication: "2022-10-03T09:05:00",
    title: "EDWIN ERNESTO CEDILLOS-RODRIGUEZ",
    coordinates: [],
    hair_raw: null,
    languages: ["Spanish"],
    complexion: null,
    build: null,
    details: null,
    status: "na",
    legat_names: null,
    eyes: null,
    person_classification: "Main",
    description:
      "Conspiracy to Provide and Conceal Material Support and Resources to Terrorists; Narco-Terrorism Conspiracy; Racketeering Conspiracy",
    images: [
      {
        large:
          "https://www.fbi.gov/wanted/cei/edwin-ernesto-cedillos-rodriguez/@@images/image/large",
        caption: null,
        thumb:
          "https://www.fbi.gov/wanted/cei/edwin-ernesto-cedillos-rodriguez/@@images/image/thumb",
        original:
          "https://www.fbi.gov/wanted/cei/edwin-ernesto-cedillos-rodriguez/@@images/image",
      },
    ],
    possible_countries: null,
    weight_min: null,
    additional_information: null,
    remarks: null,
    path: "/wanted/cei/edwin-ernesto-cedillos-rodriguez",
    eyes_raw: null,
    weight_max: null,
    reward_min: 0,
    url: "https://www.fbi.gov/wanted/cei/edwin-ernesto-cedillos-rodriguez",
    possible_states: null,
    modified: "2025-01-21T00:05:16+00:00",
    reward_max: 0,
    race: "hispanic",
    height_max: null,
    place_of_birth: "Cuscatancingo, San Salvador, El Salvador",
    height_min: null,
    poster_classification: "default",
    warning_message: "SHOULD BE CONSIDERED ARMED AND DANGEROUS",
    pathId:
      "https://api.fbi.gov/@wanted-person/cd626d1aedfd4acc816a1a3a418b1472",
  },
];

export default data;
